name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Instalar dependências
        run: npm install

      - name: Rodar Tailwind build
        run: npx tailwindcss -i ./styles/styles.css -o ./styles/output.css --minify

      - name: Rodar ESLint
        run: npx eslint scripts/**/*.js
