name: Enviar alerta para o Discord

on:
  push:
    branches:
      - main

jobs:
   alert:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar alerta para Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "🚀 Um novo push/merge foi feito na branch `main`!"}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
